Repository StarLabsm/ForProject, pull requests merged in 2022-09, with the labels that each got.

#42 fix(mergify):mv mergify(#40)
  .github/mergify.yml
Labels: A-bug, PR-bug

#44 fix(mergify):change mergify.yml
  .github/mergify.yml
Labels: PR-bug

#50 fix(scripts):add aaa to stonedb_build.sh #49
  scripts/stonedb_build.sh
Labels: PR-bug

#52 feat(script):test two commit
  scripts/stonedb_build.sh
Labels: PR-feature

#54 fix(stonedb):change scripts
  scripts/stonedb_build.sh
Labels: PR-bug

#56 feat(cicd):add queue
  .github/mergify.yml
Labels: PR-feature

#57 fix(scripts): delete zsp and add asdf
  scripts/stonedb_build.sh
Labels: PR-bug

#58 fix(script):delete asdf
  scripts/stonedb_build.sh
Labels: PR-bug

#59 fix(mergify):remove squaue
  .github/mergify.yml
Labels: PR-bug

#60 fix(script):pr change stoendb_build.sh
  scripts/stonedb_build.sh
Labels: PR-bug

#61 fix(test):test11111
  scripts/stonedb_build.sh
Labels: PR-bug, PR-docs

#62 feat(script):add test pr1
  scripts/stonedb_build.sh
Labels: PR-feature

#34 docs(schema): delete one line #33
  Doxyfile-perfschema
Labels: PR-docs

#65 fix(script):test pr1-1
  scripts/stonedb_build.sh
Labels: PR-bug

#78 fix(mtr):test1
  mysql-test/t/alias.test
Labels: PR-bug

#79 fix(tt):tt2
  mysql-test/t/alias.test
Labels: PR-bug

#80 feat(a):aa
  mysql-test/t/alias.test
Labels: PR-feature
